### ISSUE TITLE
How To run Project without code inside my images?

### ISSUE THREAD

**Issue by bestony** [WesleyE/Laravel-Docker#1]
Hi, WesleyE,

I want to run my laravel project in docker .

but i think the best practice is my code outside images  , and mount code  by command.

But, when i  run my code `docker run wesleyelfring/laravel -d -v /Users/bestony/Sites/lctt:/var/www/html -p 81:80`  , i got an error 

```
Usage: apache2 [-D name] [-d directory] [-f file]
               [-C "directive"] [-c "directive"]
               [-k start|restart|graceful|graceful-stop|stop]
               [-v] [-V] [-h] [-l] [-L] [-t] [-T] [-S] [-X]
Options:
  -D name            : define a name for use in <IfDefine name> directives
  -d directory       : specify an alternate initial ServerRoot
  -f file            : specify an alternate ServerConfigFile
  -C "directive"     : process directive before reading config files
  -c "directive"     : process directive after reading config files
  -e level           : show startup errors of level (see LogLevel)
  -E file            : log startup errors to file
  -v                 : show version number
  -V                 : show compile settings
  -h                 : list available command line options (this page)
  -l                 : list compiled in modules
  -L                 : list available configuration directives
  -t -D DUMP_VHOSTS  : show parsed vhost settings
  -t -D DUMP_RUN_CFG : show parsed run settings
  -S                 : a synonym for -t -D DUMP_VHOSTS -D DUMP_RUN_CFG
  -t -D DUMP_MODULES : show all loaded modules
  -M                 : a synonym for -t -D DUMP_MODULES
  -t                 : run syntax check for config files
  -T                 : start without DocumentRoot(s) check
  -X                 : debug mode (only one worker, do not detach)
``` 

can you give me some help ?

**Comment by WesleyE** [comment]
Hi @bestony,

Without a Dockerfile, you should be able to get it running with `docker run -d -p 80:80 --name my-app -v "$PWD":/var/www/html wesleyelfring/laravel:latest`. The only thing is different is the _order_ of your  command arguments. This is the syntax:
`$ docker run [OPTIONS] IMAGE[:TAG|@DIGEST] [COMMAND] [ARG...]`

In your command, you supply all of `-d -v /Users/bestony/Sites/lctt:/var/www/html -p 81:80` to Apache instead of Docker. Simply put, all the stuff you put **after** the image name gets 'send' to the image process instead of the Docker daemon.

By the way, this image is based on the `php:7-apache` image, so you can use their original instructions. [Check them out here](https://github.com/docker-library/docs/blob/master/php/README.md).

Hope this helps!

**Comment by bestony** [comment]
Thank You, @WesleyE !
